#name: Deploy Login Service
#
#on:
#  push:
#    branches:
#      - main
#
#jobs:
#  deploy:
#    runs-on: ubuntu-22.04
#
#    steps:
#      - name: Deploy via SSH
#        uses: appleboy/ssh-action@v1.0.3
#        with:
#          host: ${{ secrets.HOST }}
#          username: deployer
#          key: ${{ secrets.SSH_KEY }}
#          port: ${{ secrets.PORT }}
#          script: |
#            set -e
#
#            cd /opt/login-service
#
#            git fetch origin main
#            git reset --hard origin/main
#
#            docker compose up -d --build